export { default as Home } from "./Home.jsx";
export { default as Profile } from "./Profile.jsx";
export { default as Dashboard } from "./dashboard/Dashboard.jsx";
export { default as Login } from "./auth/Login.jsx";
export { default as Register } from "./auth/Register.jsx";
export { default as Feed } from "./Feed.jsx";
export { default as Search } from "./Search.jsx";
export { default as Settings } from "./Settings.jsx";
export { default as Applications } from "./candidate/Applications.jsx";
